name: News Workflow -97
on:
  push:
    branches:
      - main
      - 'dev-diva'
      - 'dews-**'
    paths:
      - '.github/workflows/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version:20
      - name: Get the Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Test the Code
        run: echo"Testing code...."
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version:20
      - name: Get the Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build the Code
        run: echo"Building code...."
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version:20
      - name: Get the Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Deploy App
        run: echo "Deploying the App to Server...."
